// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NymaEshop2.Data;

namespace NymaEshop2.Migrations
{
    [DbContext(typeof(MyEshopContext))]
    [Migration("20211110135808_Seeddaacatfory")]
    partial class Seeddaacatfory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NymaEshop2.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DesvriptionCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DesvriptionCT = "Asp.Net Core 3",
                            NameCT = "Asp.Net Core"
                        },
                        new
                        {
                            Id = 2,
                            DesvriptionCT = "گروه لباس ورزشی",
                            NameCT = "لباس ورزشی"
                        },
                        new
                        {
                            Id = 3,
                            DesvriptionCT = "ساعت مچی",
                            NameCT = "ساعت مچی"
                        },
                        new
                        {
                            Id = 4,
                            DesvriptionCT = "لوازم منزل",
                            NameCT = "لوازم منزل"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
